import { CancellationToken } from "../../context/CancellationToken.js"
import { MappedKey } from "../../context/CooperationContext.js"
import { isoFromNowMillis, postgresMaxTime } from "../../../util/Clock.js"
import { combineDeadlines, DeadlineData } from "./Deadline.js"

/**
 * Deadline that applies only to rollback (compensating action) execution — it does NOT apply
 * during normal execution.
 */
export class RollbackPathDeadline
    extends CancellationToken<RollbackPathDeadline>
    implements DeadlineData
{
    constructor(
        readonly deadline: string,
        readonly source: string,
        readonly trace: DeadlineData[] = [],
    ) {
        super(RollbackPathDeadlineKey)
    }

    and(other: RollbackPathDeadline): CancellationToken<RollbackPathDeadline> {
        if (this.key !== other.key) {
            throw new Error(`Trying to mix together ${this.key.name} and ${other.key.name}`)
        }
        return combineDeadlines(
            this,
            other,
            (deadline, source, trace) => new RollbackPathDeadline(deadline, source, trace),
        )
    }
}

/**
 * Context key for rollback path deadline tokens. Serializes as "RollbackPathDeadlineKey" (the
 * original's class simple name). NOTE: the deadline give-up SQL generated by strategyBuilders'
 * `deadlineMissed(…, "rollback", …)` checks the context for 'RollbackDeadlineKey' — a different
 * name. That mismatch exists in the Kotlin original and is preserved faithfully here.
 */
export const RollbackPathDeadlineKey = new MappedKey<RollbackPathDeadline>(
    "RollbackPathDeadlineKey",
    json => new RollbackPathDeadline(json.deadline, json.source, json.trace ?? []),
)

/** Creates a rollback path deadline [timeoutMillis] from now. */
export function rollbackPathTimeout(timeoutMillis: number, source: string): RollbackPathDeadline {
    return new RollbackPathDeadline(isoFromNowMillis(timeoutMillis), source)
}

/** Creates a rollback deadline that never expires. */
export function noRollbackPathTimeout(source: string): RollbackPathDeadline {
    return new RollbackPathDeadline(postgresMaxTime, source)
}
